// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrIncrementCartItem = `-- name: AddOrIncrementCartItem :one
INSERT INTO public.cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET quantity = public.cart_items.quantity + EXCLUDED.quantity
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type AddOrIncrementCartItemParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
	Quantity  int32       `json:"quantity"`
}

func (q *Queries) AddOrIncrementCartItem(ctx context.Context, arg AddOrIncrementCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addOrIncrementCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO public.carts (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItemByID = `-- name: DeleteCartItemByID :exec
DELETE FROM public.cart_items
WHERE id = $1
`

func (q *Queries) DeleteCartItemByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItemByID, id)
	return err
}

const deleteCartItemsByIDs = `-- name: DeleteCartItemsByIDs :exec
DELETE FROM public.cart_items
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteCartItemsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItemsByIDs, dollar_1)
	return err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at, updated_at
FROM public.carts
WHERE user_id = $1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchCart = `-- name: TouchCart :exec
UPDATE public.carts
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchCart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCart, id)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE public.cart_items
SET quantity = $2
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
