// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrIncrementCartItem = `-- name: AddOrIncrementCartItem :one
INSERT INTO public.cart_items (
    cart_id,
    product_id,
    quantity,
    selected_attributes,
    attributes_key
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (cart_id, product_id, attributes_key)
DO UPDATE SET quantity = public.cart_items.quantity + EXCLUDED.quantity
RETURNING id, cart_id, product_id, quantity, selected_attributes, attributes_key, created_at, updated_at
`

type AddOrIncrementCartItemParams struct {
	CartID             pgtype.UUID `json:"cart_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	Quantity           int32       `json:"quantity"`
	SelectedAttributes []byte      `json:"selected_attributes"`
	AttributesKey      string      `json:"attributes_key"`
}

func (q *Queries) AddOrIncrementCartItem(ctx context.Context, arg AddOrIncrementCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addOrIncrementCartItem, arg.CartID, arg.ProductID, arg.Quantity, arg.SelectedAttributes, arg.AttributesKey)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.SelectedAttributes,
		&i.AttributesKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO public.carts (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItemByID = `-- name: DeleteCartItemByID :exec
DELETE FROM public.cart_items
WHERE id = $1
`

func (q *Queries) DeleteCartItemByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItemByID, id)
	return err
}

const deleteCartItemForUser = `-- name: DeleteCartItemForUser :one
DELETE FROM public.cart_items ci
USING public.carts c
WHERE ci.id = $1
  AND ci.cart_id = c.id
  AND c.user_id = $2
RETURNING ci.cart_id
`

type DeleteCartItemForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCartItemForUser(ctx context.Context, arg DeleteCartItemForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCartItemForUser, arg.ID, arg.UserID)
	var cartID pgtype.UUID
	err := row.Scan(&cartID)
	return cartID, err
}

const deleteCartItemsByCartID = `-- name: DeleteCartItemsByCartID :exec
DELETE FROM public.cart_items
WHERE cart_id = $1
`

func (q *Queries) DeleteCartItemsByCartID(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItemsByCartID, cartID)
	return err
}

const deleteCartItemsByIDs = `-- name: DeleteCartItemsByIDs :exec
DELETE FROM public.cart_items
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteCartItemsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItemsByIDs, dollar_1)
	return err
}

const deleteCartItemsByIDsReturningCartIDs = `-- name: DeleteCartItemsByIDsReturningCartIDs :many
DELETE FROM public.cart_items
WHERE id = ANY($1::uuid[])
RETURNING cart_id
`

func (q *Queries) DeleteCartItemsByIDsReturningCartIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, deleteCartItemsByIDsReturningCartIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var cartID pgtype.UUID
		if err := rows.Scan(&cartID); err != nil {
			return nil, err
		}
		items = append(items, cartID)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at, updated_at
FROM public.carts
WHERE user_id = $1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItemsByCartID = `-- name: ListCartItemsByCartID :many
SELECT
    ci.id AS item_id,
    ci.product_id,
    ci.selected_attributes,
    p.name,
    p.image_url,
    p.price,
    ci.quantity,
    p.status,
    p.deleted_at
FROM public.cart_items ci
JOIN public.products p ON p.id = ci.product_id
WHERE ci.cart_id = $1
ORDER BY ci.created_at ASC, ci.id ASC
`

type ListCartItemsByCartIDRow struct {
	ItemID             pgtype.UUID        `json:"item_id"`
	ProductID          pgtype.UUID        `json:"product_id"`
	SelectedAttributes []byte             `json:"selected_attributes"`
	Name               string             `json:"name"`
	ImageUrl           pgtype.Text        `json:"image_url"`
	Price              int32              `json:"price"`
	Quantity           int32              `json:"quantity"`
	Status             ProductStatus      `json:"status"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListCartItemsByCartID(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsByCartIDRow, error) {
	rows, err := q.db.Query(ctx, listCartItemsByCartID, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsByCartIDRow
	for rows.Next() {
		var i ListCartItemsByCartIDRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ProductID,
			&i.SelectedAttributes,
			&i.Name,
			&i.ImageUrl,
			&i.Price,
			&i.Quantity,
			&i.Status,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCart = `-- name: TouchCart :exec
UPDATE public.carts
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchCart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchCart, id)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE public.cart_items
SET quantity = $2
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCartItemQuantityForUser = `-- name: UpdateCartItemQuantityForUser :one
UPDATE public.cart_items ci
SET quantity = $2,
    updated_at = NOW()
FROM public.carts c
WHERE ci.id = $1
  AND ci.cart_id = c.id
  AND c.user_id = $3
RETURNING ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.created_at, ci.updated_at
`

type UpdateCartItemQuantityForUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateCartItemQuantityForUser(ctx context.Context, arg UpdateCartItemQuantityForUserParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantityForUser, arg.ID, arg.Quantity, arg.UserID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
