// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPENDING   OrderStatus = "PENDING"
	OrderStatusCONFIRMED OrderStatus = "CONFIRMED"
	OrderStatusCOMPLETED OrderStatus = "COMPLETED"
	OrderStatusCANCELLED OrderStatus = "CANCELLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type OutboxStatus string

const (
	OutboxStatusPENDING    OutboxStatus = "PENDING"
	OutboxStatusPROCESSING OutboxStatus = "PROCESSING"
	OutboxStatusRETRY      OutboxStatus = "RETRY"
	OutboxStatusSENT       OutboxStatus = "SENT"
	OutboxStatusDEAD       OutboxStatus = "DEAD"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PaymentStatus string

const (
	PaymentStatusPENDINGPAYMENT PaymentStatus = "PENDING_PAYMENT"
	PaymentStatusSUCCESS        PaymentStatus = "SUCCESS"
	PaymentStatusFAILED         PaymentStatus = "FAILED"
	PaymentStatusEXPIRED        PaymentStatus = "EXPIRED"
	PaymentStatusREFUNDED       PaymentStatus = "REFUNDED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ProductCategory string

const (
	ProductCategoryCoffee ProductCategory = "coffee"
	ProductCategoryFood   ProductCategory = "food"
	ProductCategorySnack  ProductCategory = "snack"
)

func (e *ProductCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductCategory(s)
	case string:
		*e = ProductCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductCategory: %T", src)
	}
	return nil
}

type NullProductCategory struct {
	ProductCategory ProductCategory `json:"product_category"`
	Valid           bool            `json:"valid"` // Valid is true if ProductCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ProductCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductCategory), nil
}

type ProductStatus string

const (
	ProductStatusAvailable   ProductStatus = "available"
	ProductStatusOutOfStock  ProductStatus = "out_of_stock"
	ProductStatusUnavailable ProductStatus = "unavailable"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type UserRole string

const (
	UserRoleCUSTOMER UserRole = "CUSTOMER"
	UserRolePEGAWAI  UserRole = "PEGAWAI"
	UserRoleADMIN    UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Cart struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CartItem struct {
	ID        pgtype.UUID        `json:"id"`
	CartID    pgtype.UUID        `json:"cart_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	OrderNumber string             `json:"order_number"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      OrderStatus        `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	TotalAmount int32              `json:"total_amount"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID                 pgtype.UUID        `json:"id"`
	OrderID            pgtype.UUID        `json:"order_id"`
	ProductID          pgtype.UUID        `json:"product_id"`
	CartItemID         pgtype.UUID        `json:"cart_item_id"`
	ProductName        string             `json:"product_name"`
	PriceAtCheckout    int32              `json:"price_at_checkout"`
	Quantity           int32              `json:"quantity"`
	Subtotal           int32              `json:"subtotal"`
	SelectedAttributes []byte             `json:"selected_attributes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        OutboxStatus       `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID                    pgtype.UUID        `json:"id"`
	OrderID               pgtype.UUID        `json:"order_id"`
	Status                PaymentStatus      `json:"status"`
	Amount                int32              `json:"amount"`
	PaymentMethod         pgtype.Text        `json:"payment_method"`
	MidtransOrderID       string             `json:"midtrans_order_id"`
	MidtransTransactionID pgtype.Text        `json:"midtrans_transaction_id"`
	SnapRedirectUrl       pgtype.Text        `json:"snap_redirect_url"`
	RefundAmount          pgtype.Int4        `json:"refund_amount"`
	RefundReason          pgtype.Text        `json:"refund_reason"`
	RefundedAt            pgtype.Timestamptz `json:"refunded_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PaymentRefund struct {
	ID               pgtype.UUID        `json:"id"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	MidtransRefundID pgtype.Text        `json:"midtrans_refund_id"`
	Amount           int32              `json:"amount"`
	Reason           string             `json:"reason"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       int32              `json:"price"`
	Category    ProductCategory    `json:"category"`
	Status      ProductStatus      `json:"status"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	Attributes  []byte             `json:"attributes"`
	Stock       int32              `json:"stock"`
	Rating      pgtype.Numeric     `json:"rating"`
	TotalSold   int32              `json:"total_sold"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	FullName    string             `json:"full_name"`
	Role        UserRole           `json:"role"`
	IsVerified  bool               `json:"is_verified"`
	IsActive    bool               `json:"is_active"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
