// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO public.orders (
    order_number,
    user_id,
    status,
    notes,
    total_amount,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, order_number, user_id, status, notes, total_amount, expires_at, created_at, updated_at
`

type CreateOrderParams struct {
	OrderNumber string             `json:"order_number"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      OrderStatus        `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	TotalAmount int32              `json:"total_amount"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.UserID,
		arg.Status,
		arg.Notes,
		arg.TotalAmount,
		arg.ExpiresAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.Notes,
		&i.TotalAmount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO public.order_items (
    order_id,
    product_id,
    cart_item_id,
    product_name,
    price_at_checkout,
    quantity,
    subtotal,
    selected_attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, order_id, product_id, cart_item_id, product_name, price_at_checkout, quantity, subtotal, selected_attributes, created_at
`

type CreateOrderItemParams struct {
	OrderID            pgtype.UUID `json:"order_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	CartItemID         pgtype.UUID `json:"cart_item_id"`
	ProductName        string      `json:"product_name"`
	PriceAtCheckout    int32       `json:"price_at_checkout"`
	Quantity           int32       `json:"quantity"`
	Subtotal           int32       `json:"subtotal"`
	SelectedAttributes []byte      `json:"selected_attributes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.CartItemID,
		arg.ProductName,
		arg.PriceAtCheckout,
		arg.Quantity,
		arg.Subtotal,
		arg.SelectedAttributes,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.CartItemID,
		&i.ProductName,
		&i.PriceAtCheckout,
		&i.Quantity,
		&i.Subtotal,
		&i.SelectedAttributes,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, user_id, status, notes, total_amount, expires_at, created_at, updated_at
FROM public.orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.Notes,
		&i.TotalAmount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, cart_item_id, product_name, price_at_checkout, quantity, subtotal, selected_attributes, created_at
FROM public.order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.CartItemID,
			&i.ProductName,
			&i.PriceAtCheckout,
			&i.Quantity,
			&i.Subtotal,
			&i.SelectedAttributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, order_number, user_id, status, notes, total_amount, expires_at, created_at, updated_at
FROM public.orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.Notes,
			&i.TotalAmount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE public.orders
SET status = $2,
    expires_at = CASE WHEN $2 = 'PENDING'::public.order_status THEN expires_at ELSE NULL END
WHERE id = $1
RETURNING id, order_number, user_id, status, notes, total_amount, expires_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.Notes,
		&i.TotalAmount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
