// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO public.orders (
    order_number,
    user_id,
    status,
    table_number,
    notes,
    total_amount,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, order_number, user_id, status, table_number, notes, total_amount, expires_at, created_at, updated_at
`

type CreateOrderParams struct {
	OrderNumber string             `json:"order_number"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      OrderStatus        `json:"status"`
	TableNumber pgtype.Text        `json:"table_number"`
	Notes       pgtype.Text        `json:"notes"`
	TotalAmount int32              `json:"total_amount"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderNumber,
		arg.UserID,
		arg.Status,
		arg.TableNumber,
		arg.Notes,
		arg.TotalAmount,
		arg.ExpiresAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.TotalAmount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCheckoutCartItemsForUser = `-- name: ListCheckoutCartItemsForUser :many
SELECT
    ci.id AS cart_item_id,
    ci.product_id,
    p.name AS product_name,
    p.price,
    p.category,
    p.status,
    p.attributes,
    p.stock,
    p.deleted_at,
    ci.quantity
FROM public.cart_items ci
JOIN public.carts c ON c.id = ci.cart_id
JOIN public.products p ON p.id = ci.product_id
WHERE c.user_id = $1
  AND ci.id = ANY($2::uuid[])
ORDER BY ci.created_at ASC, ci.id ASC
FOR UPDATE OF ci
`

type ListCheckoutCartItemsForUserParams struct {
	UserID      pgtype.UUID   `json:"user_id"`
	CartItemIds []pgtype.UUID `json:"cart_item_ids"`
}

type ListCheckoutCartItemsForUserRow struct {
	CartItemID  pgtype.UUID        `json:"cart_item_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	ProductName string             `json:"product_name"`
	Price       int32              `json:"price"`
	Category    ProductCategory    `json:"category"`
	Status      ProductStatus      `json:"status"`
	Attributes  []byte             `json:"attributes"`
	Stock       int32              `json:"stock"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Quantity    int32              `json:"quantity"`
}

func (q *Queries) ListCheckoutCartItemsForUser(ctx context.Context, arg ListCheckoutCartItemsForUserParams) ([]ListCheckoutCartItemsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCheckoutCartItemsForUser, arg.UserID, arg.CartItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCheckoutCartItemsForUserRow
	for rows.Next() {
		var i ListCheckoutCartItemsForUserRow
		if err := rows.Scan(
			&i.CartItemID,
			&i.ProductID,
			&i.ProductName,
			&i.Price,
			&i.Category,
			&i.Status,
			&i.Attributes,
			&i.Stock,
			&i.DeletedAt,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingOrderItemsByCartItemIDs = `-- name: CountPendingOrderItemsByCartItemIDs :one
SELECT COUNT(*)::bigint
FROM public.order_items oi
JOIN public.orders o ON o.id = oi.order_id
WHERE o.user_id = $1
  AND o.status = 'PENDING'
  AND oi.cart_item_id = ANY($2::uuid[])
`

type CountPendingOrderItemsByCartItemIDsParams struct {
	UserID      pgtype.UUID   `json:"user_id"`
	CartItemIds []pgtype.UUID `json:"cart_item_ids"`
}

func (q *Queries) CountPendingOrderItemsByCartItemIDs(ctx context.Context, arg CountPendingOrderItemsByCartItemIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOrderItemsByCartItemIDs, arg.UserID, arg.CartItemIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listExpiredPendingOrdersByCartItemIDs = `-- name: ListExpiredPendingOrdersByCartItemIDs :many
SELECT DISTINCT o.id, o.order_number, o.user_id, o.status, o.table_number, o.notes, o.total_amount, o.expires_at, o.created_at, o.updated_at
FROM public.orders o
JOIN public.order_items oi ON oi.order_id = o.id
WHERE o.user_id = $1
  AND o.status = 'PENDING'
  AND o.expires_at IS NOT NULL
  AND o.expires_at <= $2
  AND oi.cart_item_id = ANY($3::uuid[])
ORDER BY o.created_at ASC, o.id ASC
`

type ListExpiredPendingOrdersByCartItemIDsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CartItemIds []pgtype.UUID      `json:"cart_item_ids"`
}

func (q *Queries) ListExpiredPendingOrdersByCartItemIDs(ctx context.Context, arg ListExpiredPendingOrdersByCartItemIDsParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrdersByCartItemIDs, arg.UserID, arg.ExpiresAt, arg.CartItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.TableNumber,
			&i.Notes,
			&i.TotalAmount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const acquireOrderNumberDateLock = `-- name: AcquireOrderNumberDateLock :exec
SELECT pg_advisory_xact_lock(hashtext($1))
`

func (q *Queries) AcquireOrderNumberDateLock(ctx context.Context, dateKey string) error {
	_, err := q.db.Exec(ctx, acquireOrderNumberDateLock, dateKey)
	return err
}

const countOrdersByOrderNumberPrefix = `-- name: CountOrdersByOrderNumberPrefix :one
SELECT COUNT(*)::bigint
FROM public.orders
WHERE order_number LIKE $1 || '%'
`

func (q *Queries) CountOrdersByOrderNumberPrefix(ctx context.Context, prefix string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByOrderNumberPrefix, prefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lockProductByIDForUpdate = `-- name: LockProductByIDForUpdate :one
SELECT id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
FROM public.products
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockProductByIDForUpdate(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, lockProductByIDForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockOrderByIDForUpdate = `-- name: LockOrderByIDForUpdate :one
SELECT id, order_number, user_id, status, table_number, notes, total_amount, expires_at, created_at, updated_at
FROM public.orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockOrderByIDForUpdate(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, lockOrderByIDForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.TotalAmount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementProductStock = `-- name: DecrementProductStock :one
UPDATE public.products
SET stock = stock - $2
WHERE id = $1
  AND stock >= $2
RETURNING id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
`

type DecrementProductStockParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, decrementProductStock, arg.ID, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementProductStock = `-- name: IncrementProductStock :one
UPDATE public.products
SET stock = stock + $2
WHERE id = $1
RETURNING id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
`

type IncrementProductStockParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) IncrementProductStock(ctx context.Context, arg IncrementProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, incrementProductStock, arg.ID, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementProductTotalSold = `-- name: IncrementProductTotalSold :one
UPDATE public.products
SET total_sold = total_sold + $2
WHERE id = $1
RETURNING id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
`

type IncrementProductTotalSoldParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) IncrementProductTotalSold(ctx context.Context, arg IncrementProductTotalSoldParams) (Product, error) {
	row := q.db.QueryRow(ctx, incrementProductTotalSold, arg.ID, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO public.order_items (
    order_id,
    product_id,
    cart_item_id,
    product_name,
    price_at_checkout,
    quantity,
    subtotal,
    selected_attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, order_id, product_id, cart_item_id, product_name, price_at_checkout, quantity, subtotal, selected_attributes, created_at
`

type CreateOrderItemParams struct {
	OrderID            pgtype.UUID `json:"order_id"`
	ProductID          pgtype.UUID `json:"product_id"`
	CartItemID         pgtype.UUID `json:"cart_item_id"`
	ProductName        string      `json:"product_name"`
	PriceAtCheckout    int32       `json:"price_at_checkout"`
	Quantity           int32       `json:"quantity"`
	Subtotal           int32       `json:"subtotal"`
	SelectedAttributes []byte      `json:"selected_attributes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.CartItemID,
		arg.ProductName,
		arg.PriceAtCheckout,
		arg.Quantity,
		arg.Subtotal,
		arg.SelectedAttributes,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.CartItemID,
		&i.ProductName,
		&i.PriceAtCheckout,
		&i.Quantity,
		&i.Subtotal,
		&i.SelectedAttributes,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, user_id, status, table_number, notes, total_amount, expires_at, created_at, updated_at
FROM public.orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.TotalAmount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, cart_item_id, product_name, price_at_checkout, quantity, subtotal, selected_attributes, created_at
FROM public.order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.CartItemID,
			&i.ProductName,
			&i.PriceAtCheckout,
			&i.Quantity,
			&i.Subtotal,
			&i.SelectedAttributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, order_number, user_id, status, table_number, notes, total_amount, expires_at, created_at, updated_at
FROM public.orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.TableNumber,
			&i.Notes,
			&i.TotalAmount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT
    id,
    order_number,
    user_id,
    status,
    table_number,
    total_amount,
    created_at
FROM public.orders
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::text = '' OR status = NULLIF($2, '')::public.order_status)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListOrdersParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListOrdersRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrderNumber string             `json:"order_number"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      OrderStatus        `json:"status"`
	TableNumber pgtype.Text        `json:"table_number"`
	TotalAmount int32              `json:"total_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.Status,
			&i.TableNumber,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE public.orders
SET status = $2,
    expires_at = CASE WHEN $2 = 'PENDING'::public.order_status THEN expires_at ELSE NULL END
WHERE id = $1
RETURNING id, order_number, user_id, status, table_number, notes, total_amount, expires_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.Status,
		&i.TableNumber,
		&i.Notes,
		&i.TotalAmount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
