// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO public.outbox_events (
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    status,
    retry_count,
    next_retry_at
) VALUES (
    $1, $2, $3, $4, 'PENDING', 0, NOW()
)
RETURNING id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, next_retry_at, last_error, created_at, updated_at
`

type CreateOutboxEventParams struct {
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPendingOutboxEvents = `-- name: LockPendingOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, next_retry_at, last_error, created_at, updated_at
FROM public.outbox_events
WHERE status IN ('PENDING', 'RETRY')
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxProcessing = `-- name: MarkOutboxProcessing :exec
UPDATE public.outbox_events
SET status = 'PROCESSING'
WHERE id = $1
`

func (q *Queries) MarkOutboxProcessing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxProcessing, id)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE public.outbox_events
SET status = CASE WHEN $3 THEN 'DEAD' ELSE 'RETRY' END,
    retry_count = retry_count + 1,
    next_retry_at = $2,
    last_error = $4
WHERE id = $1
`

type MarkOutboxRetryParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	Status      OutboxStatus       `json:"status"`
	LastError   pgtype.Text        `json:"last_error"`
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxRetry,
		arg.ID,
		arg.NextRetryAt,
		arg.Status,
		arg.LastError,
	)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE public.outbox_events
SET status = 'SENT',
    last_error = NULL,
    next_retry_at = NULL
WHERE id = $1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxSent, id)
	return err
}
