// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO public.payments (
    order_id,
    status,
    amount,
    midtrans_order_id,
    snap_redirect_url
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, order_id, status, amount, payment_method, midtrans_order_id, midtrans_transaction_id, snap_redirect_url, refund_amount, refund_reason, refunded_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID         pgtype.UUID   `json:"order_id"`
	Status          PaymentStatus `json:"status"`
	Amount          int32         `json:"amount"`
	MidtransOrderID string        `json:"midtrans_order_id"`
	SnapRedirectUrl pgtype.Text   `json:"snap_redirect_url"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Status,
		arg.Amount,
		arg.MidtransOrderID,
		arg.SnapRedirectUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.PaymentMethod,
		&i.MidtransOrderID,
		&i.MidtransTransactionID,
		&i.SnapRedirectUrl,
		&i.RefundAmount,
		&i.RefundReason,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentRefund = `-- name: CreatePaymentRefund :one
INSERT INTO public.payment_refunds (
    payment_id,
    midtrans_refund_id,
    amount,
    reason,
    created_by
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, payment_id, midtrans_refund_id, amount, reason, created_by, created_at
`

type CreatePaymentRefundParams struct {
	PaymentID        pgtype.UUID `json:"payment_id"`
	MidtransRefundID pgtype.Text `json:"midtrans_refund_id"`
	Amount           int32       `json:"amount"`
	Reason           string      `json:"reason"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePaymentRefund(ctx context.Context, arg CreatePaymentRefundParams) (PaymentRefund, error) {
	row := q.db.QueryRow(ctx, createPaymentRefund,
		arg.PaymentID,
		arg.MidtransRefundID,
		arg.Amount,
		arg.Reason,
		arg.CreatedBy,
	)
	var i PaymentRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.MidtransRefundID,
		&i.Amount,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePaymentByOrderID = `-- name: GetActivePaymentByOrderID :one
SELECT id, order_id, status, amount, payment_method, midtrans_order_id, midtrans_transaction_id, snap_redirect_url, refund_amount, refund_reason, refunded_at, created_at, updated_at
FROM public.payments
WHERE order_id = $1
  AND status = 'PENDING_PAYMENT'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActivePaymentByOrderID(ctx context.Context, orderID pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getActivePaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.PaymentMethod,
		&i.MidtransOrderID,
		&i.MidtransTransactionID,
		&i.SnapRedirectUrl,
		&i.RefundAmount,
		&i.RefundReason,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByOrderID = `-- name: ListPaymentsByOrderID :many
SELECT id, order_id, status, amount, payment_method, midtrans_order_id, midtrans_transaction_id, snap_redirect_url, refund_amount, refund_reason, refunded_at, created_at, updated_at
FROM public.payments
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Status,
			&i.Amount,
			&i.PaymentMethod,
			&i.MidtransOrderID,
			&i.MidtransTransactionID,
			&i.SnapRedirectUrl,
			&i.RefundAmount,
			&i.RefundReason,
			&i.RefundedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentRefunded = `-- name: MarkPaymentRefunded :one
UPDATE public.payments
SET status = 'REFUNDED',
    refund_amount = $2,
    refund_reason = $3,
    refunded_at = NOW()
WHERE id = $1
RETURNING id, order_id, status, amount, payment_method, midtrans_order_id, midtrans_transaction_id, snap_redirect_url, refund_amount, refund_reason, refunded_at, created_at, updated_at
`

type MarkPaymentRefundedParams struct {
	ID           pgtype.UUID `json:"id"`
	RefundAmount pgtype.Int4 `json:"refund_amount"`
	RefundReason pgtype.Text `json:"refund_reason"`
}

func (q *Queries) MarkPaymentRefunded(ctx context.Context, arg MarkPaymentRefundedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentRefunded, arg.ID, arg.RefundAmount, arg.RefundReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.PaymentMethod,
		&i.MidtransOrderID,
		&i.MidtransTransactionID,
		&i.SnapRedirectUrl,
		&i.RefundAmount,
		&i.RefundReason,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentAfterWebhook = `-- name: UpdatePaymentAfterWebhook :one
UPDATE public.payments
SET status = $2,
    payment_method = $3,
    midtrans_transaction_id = $4,
    snap_redirect_url = CASE
        WHEN $2 IN ('SUCCESS', 'FAILED', 'EXPIRED', 'REFUNDED') THEN NULL
        ELSE snap_redirect_url
    END
WHERE id = $1
RETURNING id, order_id, status, amount, payment_method, midtrans_order_id, midtrans_transaction_id, snap_redirect_url, refund_amount, refund_reason, refunded_at, created_at, updated_at
`

type UpdatePaymentAfterWebhookParams struct {
	ID                    pgtype.UUID   `json:"id"`
	Status                PaymentStatus `json:"status"`
	PaymentMethod         pgtype.Text   `json:"payment_method"`
	MidtransTransactionID pgtype.Text   `json:"midtrans_transaction_id"`
}

func (q *Queries) UpdatePaymentAfterWebhook(ctx context.Context, arg UpdatePaymentAfterWebhookParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentAfterWebhook,
		arg.ID,
		arg.Status,
		arg.PaymentMethod,
		arg.MidtransTransactionID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.PaymentMethod,
		&i.MidtransOrderID,
		&i.MidtransTransactionID,
		&i.SnapRedirectUrl,
		&i.RefundAmount,
		&i.RefundReason,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
