// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO public.products (
    name,
    description,
    price,
    category,
    status,
    image_url,
    attributes,
    stock
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Price       int32           `json:"price"`
	Category    ProductCategory `json:"category"`
	Status      ProductStatus   `json:"status"`
	ImageUrl    pgtype.Text     `json:"image_url"`
	Attributes  []byte          `json:"attributes"`
	Stock       int32           `json:"stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.Status,
		arg.ImageUrl,
		arg.Attributes,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
FROM public.products
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByNameCI = `-- name: GetProductByNameCI :one
SELECT id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
FROM public.products
WHERE LOWER(name) = LOWER($1)
  AND deleted_at IS NULL
`

func (q *Queries) GetProductByNameCI(ctx context.Context, lower string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByNameCI, lower)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
FROM public.products
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Status,
			&i.ImageUrl,
			&i.Attributes,
			&i.Stock,
			&i.Rating,
			&i.TotalSold,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStatus = `-- name: UpdateProductStatus :one
UPDATE public.products
SET status = $2
WHERE id = $1
RETURNING id, name, description, price, category, status, image_url, attributes, stock, rating, total_sold, created_at, updated_at, deleted_at
`

type UpdateProductStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status ProductStatus `json:"status"`
}

func (q *Queries) UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStatus, arg.ID, arg.Status)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Status,
		&i.ImageUrl,
		&i.Attributes,
		&i.Stock,
		&i.Rating,
		&i.TotalSold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
