// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrIncrementCartItem(ctx context.Context, arg AddOrIncrementCartItemParams) (CartItem, error)
	CreateCart(ctx context.Context, userID pgtype.UUID) (Cart, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentRefund(ctx context.Context, arg CreatePaymentRefundParams) (PaymentRefund, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteCartItemByID(ctx context.Context, id pgtype.UUID) error
	DeleteCartItemForUser(ctx context.Context, arg DeleteCartItemForUserParams) (pgtype.UUID, error)
	DeleteCartItemsByCartID(ctx context.Context, cartID pgtype.UUID) error
	DeleteCartItemsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) error
	GetActivePaymentByOrderID(ctx context.Context, orderID pgtype.UUID) (Payment, error)
	GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductByNameCI(ctx context.Context, lower string) (Product, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error)
	ListCartItemsByCartID(ctx context.Context, cartID pgtype.UUID) ([]ListCartItemsByCartIDRow, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error)
	ListPaymentsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Payment, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	LockPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	MarkOutboxProcessing(ctx context.Context, id pgtype.UUID) error
	MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error
	MarkOutboxSent(ctx context.Context, id pgtype.UUID) error
	MarkPaymentRefunded(ctx context.Context, arg MarkPaymentRefundedParams) (Payment, error)
	RestoreProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	SoftDeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	TouchCart(ctx context.Context, id pgtype.UUID) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateCartItemQuantityForUser(ctx context.Context, arg UpdateCartItemQuantityForUserParams) (CartItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePaymentAfterWebhook(ctx context.Context, arg UpdatePaymentAfterWebhookParams) (Payment, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
}

var _ Querier = (*Queries)(nil)
