// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRevenueReport = `-- name: GetRevenueReport :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total_revenue
FROM public.payments
WHERE status = 'SUCCESS'
  AND ($1::timestamptz IS NULL OR created_at >= $1)
  AND ($2::timestamptz IS NULL OR created_at < $2)
`

type GetRevenueReportParams struct {
	DateFrom pgtype.Timestamptz `json:"date_from"`
	DateTo   pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) GetRevenueReport(ctx context.Context, arg GetRevenueReportParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRevenueReport, arg.DateFrom, arg.DateTo)
	var totalRevenue int64
	err := row.Scan(&totalRevenue)
	return totalRevenue, err
}

const listProductsSoldReport = `-- name: ListProductsSoldReport :many
SELECT
    oi.product_id,
    oi.product_name,
    COALESCE(SUM(oi.quantity), 0)::integer AS quantity_sold
FROM public.order_items oi
JOIN public.orders o ON o.id = oi.order_id
WHERE o.status IN ('CONFIRMED', 'COMPLETED')
  AND EXISTS (
      SELECT 1
      FROM public.payments p
      WHERE p.order_id = o.id
        AND p.status = 'SUCCESS'
        AND ($1::timestamptz IS NULL OR p.created_at >= $1)
        AND ($2::timestamptz IS NULL OR p.created_at < $2)
  )
GROUP BY oi.product_id, oi.product_name
ORDER BY quantity_sold DESC, oi.product_name ASC
`

type ListProductsSoldReportParams struct {
	DateFrom pgtype.Timestamptz `json:"date_from"`
	DateTo   pgtype.Timestamptz `json:"date_to"`
}

type ListProductsSoldReportRow struct {
	ProductID    pgtype.UUID `json:"product_id"`
	ProductName  string      `json:"product_name"`
	QuantitySold int32       `json:"quantity_sold"`
}

func (q *Queries) ListProductsSoldReport(ctx context.Context, arg ListProductsSoldReportParams) ([]ListProductsSoldReportRow, error) {
	rows, err := q.db.Query(ctx, listProductsSoldReport, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsSoldReportRow{}
	for rows.Next() {
		var i ListProductsSoldReportRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.QuantitySold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
