// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserById = `-- name: GetUserById :one
SELECT
    id::text,
    email,
    full_name,
    role,
    is_verified,
    is_active,
    avatar_url,
    phone_number
FROM public.users
WHERE id = $1
`

type GetUserByIdRow struct {
	ID          string      `json:"id"`
	Email       string      `json:"email"`
	FullName    string      `json:"full_name"`
	Role        UserRole    `json:"role"`
	IsVerified  bool        `json:"is_verified"`
	IsActive    bool        `json:"is_active"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.IsActive,
		&i.AvatarUrl,
		&i.PhoneNumber,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE public.users
SET
    full_name = COALESCE($2, full_name),
    phone_number = COALESCE($3, phone_number),
    avatar_url = COALESCE($4, avatar_url)
WHERE id = $1
RETURNING
    id::text,
    email,
    full_name,
    role,
    is_verified,
    is_active,
    avatar_url,
    phone_number
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	FullName    pgtype.Text `json:"full_name"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.PhoneNumber,
		arg.AvatarUrl,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.IsActive,
		&i.AvatarUrl,
		&i.PhoneNumber,
	)
	return i, err
}

type UpdateUserProfileRow = GetUserByIdRow
